services:
  - type: web
    name: cobalt-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    rootDir: backend
    envVars:
      - key: API_URL
        value: https://cobalt-api.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
